### ISSUE TITLE
not working on paper

### ISSUE THREAD

**Issue by jojommeke** [akshualy/AntiSeedCracker#2]
if i enable any option in the config, it gives tons of errors(200+ (all like 19 lines)) that paper can't pas chunk load event to the plugin and with the default config it works but people can't join which gives the error that paper can't pass on join event to the plugin

**Comment by akshualy** [comment]
Which paper version are you on?

**Comment by jojommeke** [comment]
the error is exactly like discribed; something like cant pass Paper.onplayerjoin(or/login) to antiseedcracker, version is: 1.20.1-R0.1-SNAPSHOT, i will provide /version output later

**Comment by akshualy** [comment]
Hi, sorry for the late response. The `end_cities` modifier does not support 1.20.1, set it's `enabled` to `false` and the errors will disappear.
To use that modifier update to 1.20.4 or later, as that is the version the API it relies on was added.

**Comment by jojommeke** [comment]
> Hi, sorry for the late response. The `end_cities` modifier does not support 1.20.1, set it's `enabled` to `false` and the errors will disappear.
> To use that modifier update to 1.20.4 or later, as that is the version the API it relies on was added.

I did that(on 1.20.1) but the on join issue still persists and people can't join

**Comment by akshualy** [comment]
Can you please paste the **full** and **exact** error output. Without that I won't be able to see which line exactly caused the issue.

**Comment by akshualy** [comment]
After receiving the error through Discord, it turns out they were using an older version of ProtocolLib. A compatibility catch has been added with a warning on first join.
