### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by isArkaDarkTime** [akshualy/AntiSeedCracker#5]
Hello! On player join or respawn to console send warn:
[AntiSeedCracker]: Failed writing to login packet: Field index 0 is out of bounds for length 0

**Comment by akshualy** [comment]
Hi, what's your server and ProtocolLib version?

**Comment by isArkaDarkTime** [comment]
> Hi, what's your server and ProtocolLib version?

Hello again, 5.2.0-SNAPSHOT-679

**Comment by akshualy** [comment]
Hey, you can try this temporary fix:

[AntiSeedCracker-1.2.2.jar.zip](https://github.com/user-attachments/files/16323652/AntiSeedCracker-1.2.2.jar.zip)
Just unpack it and use the jar inside there.
I won't upload it to Spigot because I'm in the process of migrating to PacketEvents instead of ProtocolLib for the next update.

**Comment by isArkaDarkTime** [comment]
> Hey, you can try this temporary fix:
> 
> [AntiSeedCracker-1.2.2.jar.zip](https://github.com/user-attachments/files/16323652/AntiSeedCracker-1.2.2.jar.zip) Just unpack it and use the jar inside there. I won't upload it to Spigot because I'm in the process of migrating to PacketEvents instead of ProtocolLib for the next update.

Okay, thank you!

**Comment by isArkaDarkTime** [comment]
> Hey, you can try this temporary fix:
> 
> [AntiSeedCracker-1.2.2.jar.zip](https://github.com/user-attachments/files/16323652/AntiSeedCracker-1.2.2.jar.zip) Just unpack it and use the jar inside there. I won't upload it to Spigot because I'm in the process of migrating to PacketEvents instead of ProtocolLib for the next update.

Oh, my server version 1.20.1, AntiSeedCracker send error:
[16:12:25 WARN] [AntiSeedCracker]: You're running an unsupported version of Minecraft. Please update when possible.

**Comment by akshualy** [comment]
Yes, that's a warning, not an error. (Hence the word WARN and not ERROR). Unsupported means that the structure replacement feature won't work (it was added in 1.20.4). But if that's not important to you, you can ignore it.

**Comment by isArkaDarkTime** [comment]
> Yes, that's a warning, not an error. (Hence the word WARN and not ERROR). Unsupported means that the structure replacement feature won't work (it was added in 1.20.4). But if that's not important to you, you can ignore it.

Okay, thank you! You are a cool developer, don’t give up on this, thank you again!
(ps. I know what a warning and an error are :>)
