### ISSUE TITLE
Failed writing to login packet: Field index 0 is out of bounds for length 0 when logging

### ISSUE THREAD

**Issue by lamya3** [akshualy/AntiSeedCracker#7]
[10:50:08 WARN]: [AntiSeedCracker] Failed writing to login packet: Field index 0 is out of bounds for length 0

**Comment by lamya3** [comment]
AntiSeedCracker-1.2.1

LeavesMC 1.20.1

ProtocolLib version: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

In fact, there's no abnormalities occurred in game (maybe?) but server console throw this warning.

**Comment by akshualy** [comment]
Please check out this comment, the file here should work for you as well.
I can't release it as the code used is already migrated to a different packet manager.

https://github.com/akshualy/AntiSeedCracker/issues/5#issuecomment-2241541925
